#!/usr/bin/env python3


from asyncio import run

from markdown_live_preview.server.main import main

if __name__ == "__main__":
    try:
        run(main())
    except KeyboardInterrupt:
        exit()
