---
name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *" # daily

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Install Python
        uses: actions/setup-python@v3

      - name: Install Node.js
        uses: actions/setup-node@v3

      - name: Checkout
        uses: actions/checkout@v3


      - name: Install NPM Packages
        run: |-
          make init

      - name: Build
        run: |-
          make build

      - name: Release
        shell: python
        run: |-
          from setuptools import setup
          from sys import argv
          argv.extend(("sdist", "bdist_wheel"))
          setup()
