---
name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *" # daily

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Install Python
        uses: actions/setup-python@v3

      - name: Install Node.js
        uses: actions/setup-node@v3

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Toml
        run: pip install -- toml

      - name: Install Pip Packages
        shell: python
        run: |-
          from itertools import chain
          from os import execl
          from sys import executable
          from toml import load

          toml = load("pyproject.toml")
          project = toml["project"]
          execl(
            executable,
            executable,
            "-m",
            "pip",
            "install",
            "--upgrade",
            "--",
            *project["dependencies"],
            *chain.from_iterable(project["optional-dependencies"].values()),
          )

      - name: Install NPM Packages
        run: npm install

      - name: Build
        run: ./build.py

      - name: Release
        shell: python
        run: |-
          from setuptools import setup
          from sys import argv
          argv.extend(("sdist", "bdist_wheel"))
          setup()
