---
name: Release

on:
  push:
    branches:
      - md
    paths:
      - "pyproject.toml"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Install Python
        uses: actions/setup-python@v3

      - name: Install Node.js
        uses: actions/setup-node@v3

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Pip Packages
        shell: python
        run: |-
          from itertools import chain
          from os import execl
          from sys import executable

          from tomllib import load

          with open("pyproject.toml", "rb") as fd:
              toml = load(fd)
          project = toml["project"]
          execl(
              executable,
              executable,
              "-m",
              "pip",
              "install",
              "--upgrade",
              "--",
              *project["dependencies"],
              *chain.from_iterable(project["optional-dependencies"].values()),
          )

      - name: Install NPM Packages
        run: npm install

      - name: Build
        run: ./build.py

      - name: Release
        shell: python
        run: |-
          from setuptools import setup
          from sys import argv
          argv.extend(("sdist", "bdist_wheel"))
          setup()

      - name: Publish PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}
