---
name: Release

on:
  push:
    branches:
      - md
    paths:
      - "pyproject.toml"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Install Python
        uses: actions/setup-python@v3

      - name: Install Node.js
        uses: actions/setup-node@v3

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |-
          make build

      - name: Release
        run: |-
          make release

      - name: Publish PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}
